### ISSUE TITLE
Deleting Ressources is sometimes not possible

### ISSUE THREAD

**Issue by CalvinDO** [hs-furtwangen/FUDGE#43]

**Comment by CalvinDO** [comment]
Serializer.ts:275 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at MeshGLTF.serialize (Serializer.ts:275:25)
    at MeshGLTF.serialize (MeshGLTF.ts:18:50)
    at Serializer.serialize (Serializer.ts:96:37)
    at Project.serialize (Project.ts:328:48)
    at ControllerTreeResource.delete (ControllerTreeResource.ts:166:66)
    at Tree.hndDelete (Tree.ts:191:53)
    at TreeItem.hndKey (TreeItem.ts:231:16)
